CREATE DATABASE [node_db]
GO

CREATE TABLE [dbo].[USER_ACCOUNT]
(
	[username] [nvarchar](50) NULL,
	[password] [nvarchar](50) NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
	CONSTRAINT [PK_USER_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO